[versions]
minSdk = "23"
targetSdk = "34"
androidx-appcompat = "1.6.1"
androidx-compose-ui = "1.5.4"
androidx-material3 = "1.1.2"
material = "1.10.0"
androidx-activity = "1.8.1"
androidx-core = "1.12.0"
androidx-lifecycle = "2.6.2"

#plugins
android-gradle-plugin = "8.2.2"
kotlin = "1.9.21"
gradleCacheFix = "3.0"
dokka = "1.9.10"
vanniktech-maven-publish = "0.25.3"
zoomable = "0.7.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-material3" }
androidx-compose-bom = "androidx.compose:compose-bom:2023.10.01"
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
material = { module = "com.google.android.material:material", version.ref = "material" }
dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "zoomable" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
gradle-cachefix = { id = "org.gradle.android.cache-fix", version.ref = "gradleCacheFix" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
