[versions]
cronetApi = "119.6045.31"
cronetOkhttp = "0.1.0"
minSdk = "23"
playServicesCronet = "18.0.1"
targetSdk = "34"
androidx-appcompat = "1.6.1"
androidx-compose-ui = "1.6.0"
androidx-material3 = "1.1.2"
material = "1.11.0"
androidx-activity = "1.8.2"
androidx-core = "1.12.0"
androidx-lifecycle = "2.7.0"
okhttp = "4.12.0"

#plugins
android-gradle-plugin = "8.2.2"
kotlin = "1.9.22"
gradleCacheFix = "3.0"
dokka = "1.9.10"
vanniktech-maven-publish = "0.25.3"
zoomable = "0.7.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-material3" }
androidx-compose-bom = "androidx.compose:compose-bom:2024.01.00"
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
cronet-api = { module = "org.chromium.net:cronet-api", version.ref = "cronetApi" }
cronet-okhttp = { module = "com.google.net.cronet:cronet-okhttp", version.ref = "cronetOkhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-cronet = { module = "com.google.android.gms:play-services-cronet", version.ref = "playServicesCronet" }
zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "zoomable" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
gradle-cachefix = { id = "org.gradle.android.cache-fix", version.ref = "gradleCacheFix" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
